services:
  ha-stack:
    image: fiqri/ha-stack:1.3
    container_name: ha-stack
    hostname: serverA
    network_mode: host
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Asia/Jakarta}
    volumes:
      - /etc/corosync:/etc/corosync
      - /etc/pacemaker:/etc/pacemaker
      - /var/lib/pacemaker:/var/lib/pacemaker
      - /var/lib/pcsd:/var/lib/pcsd
      - /var/log/cluster:/var/log
      - /dev:/dev
      - /lib/modules:/lib/modules:ro
      - /mnt:/mnt:rshared
      - /usr/bin/docker:/usr/bin/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ../supervisor/supervisord.conf:/etc/supervisor/supervisord.conf:ro
      - ../supervisor/pacemaker.conf:/etc/supervisor/conf.d/pacemaker.conf:ro
      - ../pcs-scripts:/cluster/pcs-scripts:ro
      - ../corosync/corosync.conf:/etc/corosync/corosync.conf:ro
    extra_hosts:
      - "serverA:192.168.56.27"
      - "serverB:192.168.56.28"
    healthcheck:
      test: ["CMD-SHELL", "corosync-cmapctl totem.nodeid >/dev/null 2>&1"]
      interval: 10s
      timeout: 3s
      retries: 15
      start_period: 20s
